version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    restart: always
#    environment:
#      PMA_HOST: db
#      PMA_USER: root
#      PMA_PASSWORD: root
#    ports:
#      - "8084:80"
#services:
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'db'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'user'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'pass'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'pass'
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '3306:3306'
#    expose:
#      # Opens port 3306 on the container
#      - '3306'
#      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
## Names our volume
#volumes:
#  my-db: