spring:
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://127.0.0.1:3306/test_db}
    username: ${DB_USER:test}
    password: ${DB_PASSWORD:test}

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  port: 8083

api:
  base-url: ${API_BASE_URL:http://127.0.0.1:8080}