version: '3.1'
services:
  api:
    container_name: api
    image: api
    build:
      context: ../api
      dockerfile: ../api/Dockerfile
    #command: java -Xmx512m -Xms512m -jar menus-connect-api.jar --external.config.location="/app/config"
    restart: always
    working_dir: /app/
    ports:
      - '8080:8080'
#    depends_on:
#      - fluentd
  usual-api:
    container_name: usual-api
    image: usual-api
    build:
      context: ../usual-api
      dockerfile: ../usual-api/Dockerfile
    #command: java -Xmx512m -Xms512m -jar menus-connect-api.jar --external.config.location="/app/config"
    restart: always
    working_dir: /app/
    ports:
      - '8082:8082'
    depends_on:
      - db
      - api
  webflux-api:
    container_name: webflux-api
    image: webflux-api
    build:
      context: ../webflux-api
      dockerfile: ../webflux-api/Dockerfile
    #command: java -Xmx512m -Xms512m -jar menus-connect-api.jar --external.config.location="/app/config"
    restart: always
    working_dir: /app/
    ports:
      - '8083:8083'
    depends_on:
      - db
      - api
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'test'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'test'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"