spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:reactive"
    username: sa
    password: sa
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
server:
    port: 8081