spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/test_db}
    username: ${DB_USER:test}
    password: ${DB_PASSWORD:test}
    #driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.show-sql: true
server:
    port: 8082
api:
  base-url: ${API_BASE_URL:http://127.0.0.1:8080/user}